#ifndef CONSTANTS_H_
#define CONSTANTS_H_

enum
{
	D3D11_VS_OUTPUT_REGISTER_COUNT = 32,
	D3D11_SHADER_MAJOR_VERSION = 5,
	D3D11_SIMULTANEOUS_RENDER_TARGET_COUNT = 8,

    MAX_VERTEX_ATTRIBS = 16,
    MAX_TEXTURE_IMAGE_UNITS = 16,
	MAX_TEXTURE_IMAGE_UNITS_VTF_SN4 = 16,

    // Implementation upper limits, real maximums depend on the hardware
    IMPLEMENTATION_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 16,
    IMPLEMENTATION_MAX_COMBINED_TEXTURE_IMAGE_UNITS = MAX_TEXTURE_IMAGE_UNITS + IMPLEMENTATION_MAX_VERTEX_TEXTURE_IMAGE_UNITS,    

    IMPLEMENTATION_MAX_VARYING_VECTORS = 32,
    IMPLEMENTATION_MAX_DRAW_BUFFERS = 8,
	MAX_VERTEX_UNIFORM_VECTORS_D3D11 = 1024,
	MAX_FRAGMENT_UNIFORM_VECTORS_D3D11 = 1024
};

const float ALIASED_LINE_WIDTH_RANGE_MIN = 1.0f;
const float ALIASED_LINE_WIDTH_RANGE_MAX = 1.0f;
const float ALIASED_POINT_SIZE_RANGE_MIN = 1.0f;

static CoordinateSystemType coordinateSystem;


#endif // LIBGLESV2_CONSTANTS_H_
